source "https://rubygems.org"
gem 'pry'
gem 'nokogiri', '1.6.6.2'
gem 'Justice_League'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in Justice_League.gemspec
gemspec
